<?xml version="1.0"?>
<!--
  Copyright 2015 Fadri Furrer, ASL, ETH Zurich, Switzerland
  Copyright 2015 Michael Burri, ASL, ETH Zurich, Switzerland
  Copyright 2015 Mina Kamel, ASL, ETH Zurich, Switzerland
  Copyright 2015 Janosch Nikolic, ASL, ETH Zurich, Switzerland
  Copyright 2015 Markus Achtelik, ASL, ETH Zurich, Switzerland

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<!-- 
TODO

COMPLETE THE ARM xacro
ADD ROTOR INSIDE THE ARM
MESH FIX FOR THE ARM -->

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Macro for the inertia of a box -->
  <xacro:macro name="box_inertia" params="x y z mass">
    <inertia ixx="${0.0833333 * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
      iyy="${0.0833333 * mass * (x*x + z*z)}" iyz="0.0"
      izz="${0.0833333 * mass * (x*x + y*y)}" />
  </xacro:macro>

  <!-- Macro for the inertial properties of a box -->
  <xacro:macro name="box_inertial" params="x y z mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <xacro:box_inertia x="${x}" y="${y}" z="${z}" mass="${mass}" />
    </inertial>
  </xacro:macro>

  <!-- Main multirotor link -->
  <xacro:macro name="multirotor_base_macro"
    params="robot_namespace">
    <link name="${robot_namespace}/base_link"></link>

    <joint name="${robot_namespace}/base_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="${robot_namespace}/base_link" />
      <child link="${robot_namespace}/base_link_inertia" />
    </joint>

    <link name="${robot_namespace}/base_link_inertia">
      <inertial>
        <mass value="0.131" />  <!-- [kg] -->
        <origin xyz="-0.00694 0.00190 0.02482" />
        <inertia ixx="76498.19e-9" ixy="-138.41e-9" ixz="14011.69e-9" iyy="80911.82e-9" iyz="2914.65e-9" izz="40328.57e-9" /> 
        
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://rotors_description/meshes/body.STL" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://rotors_description/meshes/body.STL" />
        </geometry>
      </collision>
    </link>

    <!-- attach multirotor_base_plugin to the base_link -->
    <gazebo>
      <plugin filename="librotors_gazebo_multirotor_base_plugin.so" name="multirotor_base_plugin">
        <robotNamespace>${robot_namespace}</robotNamespace>
        <linkName>${robot_namespace}/base_link</linkName>
        <rotorVelocitySlowdownSim>${rotor_velocity_slowdown_sim}</rotorVelocitySlowdownSim>
      </plugin>
    </gazebo>
  </xacro:macro>


  <!-- arm joint and link -->
  <xacro:macro name="arm_rotor"
    params="robot_namespace suffix motor_number *origin color">
    <joint name="${robot_namespace}/arm_${motor_number}_joint" type="revolute" >
      <limit lower="-1.52" upper="1.52" effort="-1" velocity="-1"/>
      <dynamics damping="1" friction="1" /> 
      <xacro:insert_block name="origin" />
      <axis xyz="0 0 1" />
      <!-- <limit lower="0" upper="1" effort="-1" velocity="-1" /> -->
      <parent link="${robot_namespace}/base_link" />
     
      <child link="${robot_namespace}/arm_${motor_number}" />
      
    </joint>
    <link name="${robot_namespace}/arm_${motor_number}">
      <inertial>
        <origin xyz="24.43e-3 0 -3.82e-3" rpy="0 0 0"/>
        <mass value="0.00207" /> <!-- [kg] -->
        <inertia ixx="18.17e-9" ixy="0" ixz="-8.63e-9" iyy="434.6e-9" iyz="0" izz="420.91e-9" /> 
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://rotors_description/meshes/simple_arm.STL" />  
        </geometry>
      </visual> 
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://rotors_description/meshes/simple_arm.STL" />  
        </geometry>
      </collision>
    </link>

    <joint name="${robot_namespace}/landing_gear_${motor_number}_joint" type="fixed" >
      <origin xyz="0.0105 0 -0.012" rpy="0 0 0" />
      <parent link="${robot_namespace}/arm_${motor_number}" />
      <child link="${robot_namespace}/landing_gear_${motor_number}" />
    </joint>
    <link name="${robot_namespace}/landing_gear_${motor_number}">
      <inertial>
        <mass value="0.0051" /> <!-- [kg] -->
        <origin xyz="0 0 -6.94e-3" rpy="0 0 0" />
        <inertia ixx="41.44e-9" ixy="0" ixz="0" iyy="61.97e-9" iyz="0" izz="22.68e-9" /> 
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://rotors_description/meshes/simple_landinggear.STL" />  
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://rotors_description/meshes/simple_landinggear.STL" />  
        </geometry>
      </collision>
    </link>


    <joint name="${robot_namespace}/bumper_${motor_number}_joint" type="fixed" >
      <origin xyz="0.052 0 0" rpy="0 0 0" />
      <parent link="${robot_namespace}/arm_${motor_number}" />
      <child link="${robot_namespace}/bumper_${motor_number}" />
    </joint>
    <link name="${robot_namespace}/bumper_${motor_number}">
      <inertial>
        <mass value="0.0071" /> <!-- [kg] -->
        <origin xyz="23.51e-3 0 -3.48e-3" rpy="0 0 0" />
        <inertia ixx="302.58e-9" ixy="0" ixz="55.52" iyy="569.34e-9" iyz="0" izz="841.34e-9" /> 
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://rotors_description/meshes/simple_bumper.STL" />  
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://rotors_description/meshes/simple_bumper.STL" />  
        </geometry>
      </collision>
    </link>

    <gazebo reference="${robot_namespace}/arm_${motor_number}">
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>


  <!-- Rotor joint and link -->
  <xacro:macro name="vertical_rotor"
    params="robot_namespace suffix direction motor_constant moment_constant parent mass_rotor radius_rotor time_constant_up time_constant_down max_rot_velocity motor_number rotor_drag_coefficient rolling_moment_coefficient color use_own_mesh mesh *origin *inertia">
    <joint name="${robot_namespace}/rotor_${motor_number}_joint" type="continuous">
      <xacro:insert_block name="origin" />
      <axis xyz="0 0 1" />
      <!-- TODO(ff): not currently set because it's not yet supported -->
      <!-- <limit effort="2000" velocity="${max_rot_velocity}" /> -->
      <parent link="${parent}" />
      <child link="${robot_namespace}/rotor_${motor_number}" />
    </joint>
    <link name="${robot_namespace}/rotor_${motor_number}">
      <inertial>
        <mass value="${mass_rotor}" /> <!-- [kg] -->
        <xacro:insert_block name="inertia" />
      </inertial>
      <visual>
        <geometry>
          <!-- <cylinder length="0.005" radius="${radius_rotor}"/> --> <!-- [m] -->
          <xacro:if value="${use_own_mesh}">
            <mesh filename="${mesh}"
              scale="1 1 1" />
          </xacro:if>
          <xacro:unless value="${use_own_mesh}">
            <mesh filename="package://rotors_description/meshes/propeller_${direction}.dae"
              scale="${radius_rotor} ${radius_rotor} ${radius_rotor}" /> <!-- The propeller meshes have a radius of 1m -->
            <!-- <box size="${2*radius_rotor} 0.01 0.005"/> -->
          </xacro:unless>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.005" radius="${radius_rotor}" /> <!-- [m] -->
        </geometry>
      </collision>
    </link>
    <gazebo>
      <plugin name="${robot_namespace}_${suffix}_motor_model" filename="librotors_gazebo_motor_model.so">
        <robotNamespace>${robot_namespace}</robotNamespace>
        <jointName>${robot_namespace}/rotor_${motor_number}_joint</jointName>
        <linkName>${robot_namespace}/rotor_${motor_number}</linkName>
        <turningDirection>${direction}</turningDirection>
        <timeConstantUp>${time_constant_up}</timeConstantUp>
        <timeConstantDown>${time_constant_down}</timeConstantDown>
        <maxRotVelocity>${max_rot_velocity}</maxRotVelocity>
        <motorConstant>${motor_constant}</motorConstant>
        <momentConstant>${moment_constant}</momentConstant>
        <commandSubTopic>gazebo/command/motor_speed</commandSubTopic>
        <motorNumber>${motor_number}</motorNumber>
        <rotorDragCoefficient>${rotor_drag_coefficient}</rotorDragCoefficient>
        <rollingMomentCoefficient>${rolling_moment_coefficient}</rollingMomentCoefficient>
        <motorSpeedPubTopic>motor_speed/${motor_number}</motorSpeedPubTopic>
        <rotorVelocitySlowdownSim>${rotor_velocity_slowdown_sim}</rotorVelocitySlowdownSim>
      </plugin>
    </gazebo>
    <gazebo reference="${robot_namespace}/rotor_${motor_number}">
      <material>Gazebo/${color}</material>
    </gazebo>
  </xacro:macro>




</robot>
