<?xml version="1.0"?>
<!--
  Copyright 2022, Bilkent University Miniature Robotics Laboratory 
-->

<robot name="miniquad" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties (Taken from Novel Dynamic Inversion Architecture Design
for Quadrocopter Control by Jian Wang et al.) 
-->

  <xacro:property name="namespace" value="$(arg namespace)"/>
  <xacro:property name="rotor_velocity_slowdown_sim" value="10 " />
  <xacro:property name="use_mesh_file" value="False" />
  <xacro:property name="mesh_file" value="package://rotors_description/meshes/miniquad.dae" />
  <xacro:property name="mass" value="0.1913" /> <!-- [kg] -->
  <xacro:property name="body_width" value="0.0415" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.02" /> <!-- [m] -->
  <xacro:property name="mass_rotor" value="0.00073" /> <!-- [kg] -->
  <xacro:property name="arm_length" value="0.053" /> <!-- [m] -->
  <xacro:property name="arm_width" value="0.05" /> <!-- [m] -->
  <xacro:property name="arm_mass" value="0.001" /> <!-- [m] -->
  <xacro:property name="rotor_offset_top" value="0.005" /> <!-- [m] -->
  <xacro:property name="radius_rotor" value="0.0445" /> <!-- [m]  -->
  <xacro:property name="sin45" value="0.707106781186" />  <!-- [rad]  -->
  <xacro:property name="cos45" value="0.707106781186" /> 
  <xacro:property name="deg45" value="0.785398163" />  <!-- [rad]  -->
  <xacro:property name="motor_constant" value="7.18e-07" /> <!--[Ns/rad] -->
  <xacro:property name="moment_constant" value="0.00944" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0025" /> <!-- [s]  -->
  <xacro:property name="time_constant_down" value="0.0005" /> <!-- [s]  -->
  <xacro:property name="max_rot_velocity" value="3142" /> <!-- [rad/s] -->
  <xacro:property name="rotor_drag_coefficient" value="0" /> <!-- neglected  --> 
  <xacro:property name="rolling_moment_coefficient" value="0.000000" />  <!-- neglected / set to zero.   --> 

  <!-- Property Blocks -->
  <!-- Body inertia is experimentally determined. Taken from Amirali's Simulink simulation.  -->

  
  <xacro:property name="body_inertia">
    <inertia ixx="0.000399" ixy="0.0" ixz="0.0" iyy="0.000401" iyz="0.0" izz="0.0008" /> <!-- [kg m^2] [kg m^2] [kg m^2] [kg m^2] [kg m^2] [kg m^2] -->
  </xacro:property>

  <!-- inertia of a single rotor, assuming it is a cuboid. Height=3mm, width=15mm -->
  <xacro:property name="rotor_inertia">
    <xacro:box_inertia x="${radius_rotor}" y="0.005" z="0.00015" mass="${mass_rotor*rotor_velocity_slowdown_sim}" />
  </xacro:property>



  <!-- Included URDF Files -->
  <xacro:include filename="$(find rotors_description)/urdf/armed_base.xacro" />

  <!-- Instantiate multirotor_base_macro once -->
  <xacro:multirotor_base_macro
    robot_namespace="${namespace}">
    
  </xacro:multirotor_base_macro>


  <xacro:arm_rotor
    robot_namespace="${namespace}"
    suffix="back-right"
    motor_number="0" 
    color="Red">   
    <origin xyz="${body_width*cos45} -${body_width*sin45} 0" rpy="0 0 ${deg45*7}" />
  </xacro:arm_rotor>

    
  <xacro:arm_rotor
    robot_namespace="${namespace}"
    suffix="back-left"
    
    motor_number="1" 

    color="Red">   
    <origin xyz="${body_width*cos45} ${body_width*sin45} 0" rpy="0 0 ${deg45}" />
    
  </xacro:arm_rotor>


  <xacro:arm_rotor
    robot_namespace="${namespace}"
    suffix="front-left"
    
    motor_number="2" 

    color="Red">   
    <origin xyz="-${body_width*cos45} ${body_width*sin45} 0" rpy="0 0 ${deg45*3}" />
    
  </xacro:arm_rotor>

  <xacro:arm_rotor
    robot_namespace="${namespace}"
    suffix="front-right"
    
    motor_number="3" 
    color="Red">   
    <origin xyz="-${body_width*cos45} -${body_width*sin45} 0" rpy="0 0 ${deg45*5}" />

  </xacro:arm_rotor>
  




  <!-- Instantiate rotors -->
  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="front-right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/arm_0"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="0"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${arm_length} 0 ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="back-right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/arm_1"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${arm_length} 0 ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="back-left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/arm_2"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${arm_length} 0 ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="front-left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/arm_3"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${arm_length} 0 ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

</robot>
